## Assignment 1
#### ADTA 5550 - Summer 2020 - Marissa McKee

In [1]:
import numpy as np
import random 

#### Question 1
Create a vector (1D array) of size 20. All the elements are initialized with 0 (zero) except for the 8th element that is set with the value 8. 

In [2]:
myVector = list()
i = 0
for i in range(20):
    if i == 7:
        myVector.append(8)
    else:
        myVector.append(0)
    i+=1

print(myVector)

[0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


#### Question 2
Create a vector of size 16 with random values ranging from 0 to 63, print the vector, then sort it and print the vector again. 

In [3]:
myVector = list()
i = 0
for i in range(16):
    myVector.append(random.randint(0,63))
    i+=1

print('Unsorted',myVector)

# Sort list in place
myVector.sort()
print('Sorted',myVector)

Unsorted [45, 57, 8, 11, 25, 41, 56, 52, 8, 43, 54, 35, 20, 7, 62, 26]
Sorted [7, 8, 8, 11, 20, 25, 26, 35, 41, 43, 45, 52, 54, 56, 57, 62]


#### Question 3
Create a 5x5 matrix with values ranging from 0 to 24. 

In [4]:
myMatrix = np.random.randint(24, size=(5,5))
print('5x5 Matrix \n',myMatrix)

5x5 Matrix 
 [[13 21 19 14 21]
 [ 9  0 18  1 22]
 [19 19  2  6  5]
 [15  7 12  3  0]
 [ 6  6  0  3  6]]


#### Question 4
Create an 8x8 array with random values, then find the min and max values stored in this matrix. 

In [5]:
myMatrix = np.random.random((8,8))
print('8x8 Matrix \n',myMatrix)
print('Max Value \n',myMatrix.max(),'\nMin Value \n',myMatrix.min())

8x8 Matrix 
 [[0.88938625 0.1326964  0.34184107 0.86736479 0.78995697 0.70226321
  0.87327762 0.23638535]
 [0.72569356 0.47790422 0.59614686 0.19199283 0.98123452 0.26164304
  0.41174445 0.78211699]
 [0.9815249  0.05905456 0.300895   0.07030679 0.91136088 0.66748258
  0.94271804 0.59305075]
 [0.1242051  0.41720103 0.93161603 0.9383042  0.51516923 0.63619233
  0.31631622 0.29383969]
 [0.16315623 0.43046077 0.19910823 0.64064992 0.07295822 0.12148029
  0.79512142 0.62254742]
 [0.87969036 0.92518444 0.77100493 0.18171674 0.40182061 0.07214124
  0.89344624 0.43573878]
 [0.86457015 0.73055121 0.93465383 0.13303595 0.39191262 0.02811492
  0.64457638 0.44677947]
 [0.60528225 0.25662515 0.036221   0.8600633  0.48775266 0.40055249
  0.17100337 0.14687058]]
Max Value 
 0.9815248983324674 
Min Value 
 0.028114917472079837


#### Question 5
Create a vector of size 32 that is initialized with random values inside the range (0, 99) and then find the mean of all the initial values.

In [6]:
myVector = list()
i = 0
for i in range(32):
    myVector.append(random.randint(0,99))
    i+=1

print('Random Vector\n',myVector,'\nVector Mean\n',np.mean(myVector))

Random Vector
 [65, 76, 11, 50, 27, 77, 9, 10, 8, 45, 70, 51, 4, 1, 48, 64, 71, 29, 49, 28, 72, 93, 72, 25, 94, 7, 69, 27, 75, 28, 39, 14] 
Vector Mean
 44.0
